import React from "react";

export const getLanguages = async (value: string) => {
    const eng = {
        base: {
            login: 'Login',
            signUp: 'Sign up',
            profile: 'Profile',
            training: 'Training',
            users: 'Users',
            complexes: 'Complexes',
            Programs: 'Programs',
            Wiki: 'Wiki',
            authorization: 'Authorization',
            lblEmail: 'Your E-mail',
            lblPass: 'Your password',
            lblName: 'Your first name',
            lblLastName: 'Your last name',
            plHolName: 'Name',
            plHolLastName: 'Last name',
            plHolEmail: 'E-mail',
            plHolPass: 'Password',
            notHaveAcc: 'If you don\'t have an account',
            haveAcc: 'If you have an account',
            allUsers: 'All users',
            edit: 'Edit',
            save: 'Save',
            none: 'None',
            cancelRequest: 'Cancel request',
            removeFriend: 'Remove friend',
            addFriends: 'Add to friends',
            settings: 'Settings',
            theme: 'Theme',
            seeAllFriends: 'See all friends',
            friends: 'Friends',
        },
        settings: {
            language: 'Language',
            profile: 'Profile',
            english: "English",
            russian: "Russian",
            ukrainian: "Ukrainian",
            poland: "Poland",
        },
        training: {
            programName: 'Name of program',
            plHolProgramName: 'Enter the program name',
            errorName: 'The name must contain at least 3 letters',
            next: 'Next',
            back: 'Back',
            name: 'Name',
            type: 'Type',
            difficulty: 'Difficulty',
            days: 'Days',
            exercises: 'Exercises',
            aerobicInfo: 'Aerobic - fitness, cardio training',
            anaerobicInfo: 'Anaerobic - strength training',
            crossfitInfo: 'CrossFit - mixed training, aerobic + anaerobic',
            selectType: 'Select Program Type',
            beginner: 'Beginner',
            intermediate: 'Intermediate',
            advanced: 'Advanced',
            expert: 'Expert',
            professional: 'Professional',
            selectDifficulty: 'Select Difficulty Level',
            day: 'day',
            changeDay: 'How many training days per week?',
            generalTraining: 'day general training',
            splitTraining: 'day split workout',
            create: 'Create',
            editExercises: 'Edit Exercises',
            addExercises: 'Add exercises',
            cancel: 'Cancel',
            confirm: 'Confirm',
            createProgram: 'Create new program',
            myPrograms: 'My programs',
            secondaryMuscles: 'Secondary muscles',
            compound: 'Compound',
            none: 'None',
            finished: 'Finished training in -',
            all: 'All',
            chest: 'Chest',
            backMus: 'Back',
            biceps: 'Biceps',
            triceps: 'Triceps',
            shoulders: 'Shoulders',
            legs: 'Legs',
            abs: 'Abs',
            complete: 'Complete',
            aerobic: 'Aerobic',
            anaerobic: 'Anaerobic',
            crossfit: 'Crossfit',
            notHavePrograms: 'You don\'t have any programs yet',
        },
    };

    const rus = {
        base: {
            login: 'Войти',
            signUp: 'Реестрация',
            profile: 'Профиль',
            training: 'Тренировка',
            users: 'Пользователи',
            complexes: 'Комлпексы',
            Programs: 'Програмы',
            Wiki: 'Wiki',
            authorization: 'Авторизация',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше имя',
            lblLastName: 'Ваша фамилия',
            plHolName: 'Имя',
            plHolLastName: 'Фамилия',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Если у вас нет учетной записи',
            haveAcc: 'Если у вас есть аккаунт',
            allUsers: 'Все пользователи',
            edit: 'Редактировать',
            save: 'Сохранить',
            cancelRequest: 'Отменить запрос',
            removeFriend: 'Удалить друга',
            addFriends: 'Добавить в друзья',
            settings: 'Настройки',
            theme: 'Тема',
            seeAllFriends: 'Посмотреть всех друзей',
            friends: 'Друзья',
        },
        settings: {
            language: 'Язык',
            profile: 'Профиль',
            english: "Английский",
            russian: "Руский",
            ukrainian: "Украинский",
            poland: "Польский",
        },
        training: {
            programName: 'Название программы',
            plHolProgramName: 'Введите название программы',
            errorName: 'Имя должно содержать не менее 3 букв',
            next: 'Следующий',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Сложность',
            days: 'Дни',
            exercises: 'Упражнения',
            aerobicInfo: 'Aerobic - фитнес, кардио тренировки',
            anaerobicInfo: 'Anaerobic - силовые тренировки',
            crossfitInfo: 'CrossFit - смешанная тренировка, аэробная + анаэробная',
            selectType: 'Выберите тип программы',
            beginner: 'Начинающий',
            intermediate: 'Средний',
            advanced: 'Продвинутый',
            expert: 'Эксперт',
            professional: 'Профессиональный',
            selectDifficulty: 'Выберите уровень сложности',
            day: 'день',
            changeDay: 'Сколько тренировочных дней в неделю?',
            generalTraining: 'дневная общая тренировка',
            splitTraining: 'дневная сплит тренировка',
            create: 'Создать',
            editExercises: 'Редактировать упражнения',
            addExercises: 'Добавить упражнения',
            cancel: 'Отменить',
            confirm: 'Подтвердить',
            createProgram: 'Создать новую программу',
            myPrograms: 'Мои программы',
            secondaryMuscles: 'Вторичные мышцы',
            compound: 'Многосуставное',
            isolation: 'Изоляционное',
            none: 'Нету',
            finished: 'Закончил тренировку -',
            all: 'Все',
            chest: 'Грудные',
            backMus: 'Спина',
            biceps: 'Бицепс',
            triceps: 'Трицепс',
            shoulders: 'Плечи',
            legs: 'Ноги',
            abs: 'Прес',
            complete: 'Завершить',
            aerobic: 'Аэробная',
            anaerobic: 'Анаэробная',
            crossfit: 'Кроссфит',
            notHavePrograms: 'У вас пока нет ни одной программы',
        }
    };

    const ua = {
        base: {
            login: 'Вхід',
            signUp: 'Реєстрація',
            profile: 'Профіль',
            training: 'Тренування',
            users: 'Користувачі',
            complexes: 'Комплекси',
            Programs: 'Програми',
            Wiki: 'Wiki',
            authorization: 'Авторизація',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше Ім\'я',
            lblLastName: 'Ваше призвіще',
            plHolName: 'Ім\'я',
            plHolLastName: 'Призвіще',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Якщо у вас немає облікового запису',
            haveAcc: 'Якщо у вас є обліковий запис',
            allUsers: 'Всі користувачі',
            edit: 'Редагувати',
            save: 'Зберегти',
            cancelRequest: 'Скасувати запит',
            removeFriend: 'Видалити друга',
            addFriends: 'Додати до друзів',
            settings: 'Налаштування',
            theme: 'Тема',
            seeAllFriends: 'Переглянути всіх друзів',
            friends: 'Друзі',
        },
        settings: {
            language: 'Мова',
            profile: 'Профіль',
            english: "Англійська",
            russian: "Російська",
            ukrainian: "Українська",
            poland: "Польський",
        },
        training: {
            programName: 'Назва програми',
            plHolProgramName: 'Введіть назву програми',
            errorName: 'Ім\'я повинно містити щонайменше 3 літери',
            next: 'Далі',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Складність',
            days: 'Дні',
            exercises: 'Вправи',
            aerobicInfo: 'Aerobic - фітнес, кардіо тренування',
            anaerobicInfo: 'Anaerobic - силові тренування',
            crossfitInfo: 'CrossFit - змішане тренування, аеробне + анаеробне',
            selectType: 'Виберіть тип програми',
            beginner: 'Початківець',
            intermediate: 'Середній',
            advanced: 'Просунутий',
            expert: 'Експерт',
            professional: 'Професійний',
            selectDifficulty: 'Виберіть рівень складності',
            day: 'день',
            changeDay: 'Скільки тренувальних днів на тиждень?',
            generalTraining: 'денне загальне навчання',
            splitTraining: 'денне спліт-тренування',
            create: 'Створити',
            editExercises: 'Редагувати вправи',
            addExercises: 'Додати вправи',
            cancel: 'Відмінити',
            confirm: 'Підтвердити',
            createProgram: 'Створити нову програму',
            myPrograms: 'Мої програми',
            secondaryMuscles: 'Вторинні м\'язи',
            compound: 'Багатосуставне',
            isolation: 'Ізоляційне',
            none: 'Немає',
            finished: 'Закінчив тренування -',
            all: 'Все',
            chest: 'Грудні',
            backMus: 'Спина',
            biceps: 'Біцепс',
            triceps: 'Тріцепс',
            shoulders: 'Плечі',
            legs: 'Ноги',
            abs: 'Прес',
            complete: 'Завершити',
            aerobic: 'Аеробна',
            anaerobic: 'Анаеробна',
            crossfit: 'Кроссфіт',
            notHavePrograms: 'У вас ще немає жодних програм',
        }
    };

    const pl = {
        base: {
            login: 'Zaloguj się',
            signUp: 'Zarejestruj się',
            profile: 'Profil',
            training: 'Trening',
            users: 'Użytkownicy',
            complexes: 'Kompleksy',
            Programs: 'Programy',
            Wiki: 'Wiki',
            authorization: 'Autoryzacja',
            lblEmail: 'Twój e-mail',
            lblPass: 'Twoje hasło',
            lblName: 'Twoje imię',
            lblLastName: 'Twoje nazwisko',
            plHolName: 'Imię',
            plHolLastName: 'Nazwisko',
            plHolEmail: 'E-mail',
            plHolPass: 'Hasło',
            notHaveAcc: 'Jeśli nie masz konta',
            haveAcc: 'Jeśli masz konto',
            allUsers: 'Wszyscy użytkownicy',
            edit: 'Edytuj',
            save: 'Zapisz',
            none: 'Brak',
            cancelRequest: 'Anuluj prośbę',
            removeFriend: 'Usuń znajomego',
            addFriends: 'Dodaj do znajomych',
            settings: 'Ustawienia',
            theme: 'Motyw',
            seeAllFriends: 'Zobacz wszystkich znajomych',
            friends: 'Znajomi',
        },
        settings: {
            language: 'Język',
            profile: 'Profil',
            english: 'Angielski',
            russian: 'Rosyjski',
            ukrainian: 'Ukraiński',
            poland: "Polski",
        },
        training: {
            programName: 'Nazwa programu',
            plHolProgramName: 'Wprowadź nazwę programu',
            errorName: 'Nazwa musi zawierać co najmniej 3 litery',
            next: 'Dalej',
            back: 'Wstecz',
            name: 'Nazwa',
            type: 'Typ',
            difficulty: 'Poziom trudności',
            days: 'Dni',
            exercises: 'Ćwiczenia',
            aerobicInfo: 'Aerobik - fitness, trening cardio',
            anaerobicInfo: 'Anaerobowy - trening siłowy',
            crossfitInfo: 'CrossFit - trening mieszany, aerobowy + anaerobowy',
            selectType: 'Wybierz typ programu',
            beginner: 'Początkujący',
            intermediate: 'Średni',
            advanced: 'Zaawansowany',
            expert: 'Ekspert',
            professional: 'Profesjonalista',
            selectDifficulty: 'Wybierz poziom trudności',
            day: 'dzień',
            changeDay: 'Ile dni treningowych w tygodniu?',
            generalTraining: 'ogólny trening dzienny',
            splitTraining: 'trening dzielony dzienny',
            create: 'Utwórz',
            editExercises: 'Edytuj ćwiczenia',
            addExercises: 'Dodaj ćwiczenia',
            cancel: 'Anuluj',
            confirm: 'Potwierdź',
            createProgram: 'Utwórz nowy program',
            myPrograms: 'Moje programy',
            secondaryMuscles: 'Mięśnie pomocnicze',
            compound: 'Złożone',
            isolation: 'Izolowane',
            none: 'Brak',
            finished: 'Zakończono trening -',
            all: 'Wszystko',
            chest: 'Klatka piersiowa',
            backMus: 'Plecy',
            biceps: 'Biceps',
            triceps: 'Triceps',
            shoulders: 'Barki',
            legs: 'Nogi',
            abs: 'Brzuch',
            complete: 'Zakończ',
            aerobic: 'Aerobowy',
            anaerobic: 'Anaerobowy',
            crossfit: 'CrossFit',
        },
    };


    switch (value) {
        case 'eng' : return eng;
        case 'rus' : return rus;
        case 'ukr' : return ua;
        case 'pl' : return pl;
    }
}