import React from "react";

export const getLanguages = async (value: string) => {
    const eng = {
        base: {
            login: 'Login',
            signUp: 'Sign up',
            profile: 'Profile',
            training: 'Training',
            users: 'Users',
            complexes: 'Complexes',
            Programs: 'Programs',
            Wiki: 'Wiki',
            authorization: 'Authorization',
            lblEmail: 'Your E-mail',
            lblPass: 'Your password',
            lblName: 'Your first name',
            lblLastName: 'Your last name',
            plHolName: 'Name',
            plHolLastName: 'Last name',
            plHolEmail: 'E-mail',
            plHolPass: 'Password',
            notHaveAcc: 'If you don\'t have an account',
            haveAcc: 'If you have an account',
            allUsers: 'All users',
            edit: 'Edit',
            save: 'Save',
            none: 'None',
            cancelRequest: 'Cancel request',
            removeFriend: 'Remove friend',
            addFriends: 'Add to friends',
            settings: 'Settings',
            theme: 'Theme',
        },
        settings: {
            language: 'Language',
            profile: 'Profile',
            english: "English",
            russian: "Russian",
            ukrainian: "Ukrainian",
        },
        training: {
            programName: 'Name of program',
            plHolProgramName: 'Enter the program name',
            errorName: 'The name must contain at least 3 letters',
            next: 'Next',
            back: 'Back',
            name: 'Name',
            type: 'Type',
            difficulty: 'Difficulty',
            days: 'Days',
            exercises: 'Exercises',
            aerobicInfo: 'Aerobic - fitness, cardio training',
            anaerobicInfo: 'Anaerobic - strength training',
            crossfitInfo: 'CrossFit - mixed training, aerobic + anaerobic',
            selectType: 'Select Program Type',
            beginner: 'Beginner',
            intermediate: 'Intermediate',
            advanced: 'Advanced',
            expert: 'Expert',
            professional: 'Professional',
            selectDifficulty: 'Select Difficulty Level',
            day: 'day',
            changeDay: 'How many training days per week?',
            generalTraining: 'day general training',
            splitTraining: 'day split workout',
            create: 'Create',
            editExercises: 'Edit Exercises',
            addExercises: 'Add exercises',
            cancel: 'Cancel',
            confirm: 'Confirm',
            createProgram: 'Create new program',
            myPrograms: 'My programs',
            secondaryMuscles: 'Secondary muscles',
            compound: 'Compound',
            none: 'None',
            finished: 'Finished training in -',
            all: 'All',
            chest: 'Chest',
            backMus: 'Back',
            biceps: 'Biceps',
            triceps: 'Triceps',
            shoulders: 'Shoulders',
            legs: 'Legs',
            abs: 'Abs',
        },
    };

    const rus = {
        base: {
            login: 'Войти',
            signUp: 'Реестрация',
            profile: 'Профиль',
            training: 'Тренировка',
            users: 'Пользователи',
            complexes: 'Комлпексы',
            Programs: 'Програмы',
            Wiki: 'Wiki',
            authorization: 'Авторизация',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше имя',
            lblLastName: 'Ваша фамилия',
            plHolName: 'Имя',
            plHolLastName: 'Фамилия',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Если у вас нет учетной записи',
            haveAcc: 'Если у вас есть аккаунт',
            allUsers: 'Все пользователи',
            edit: 'Редактировать',
            save: 'Сохранить',
            cancelRequest: 'Отменить запрос',
            removeFriend: 'Удалить друга',
            addFriends: 'Добавить в друзья',
            settings: 'Настройки',
            theme: 'Тема',
        },
        settings: {
            language: 'Язык',
            profile: 'Профиль',
            english: "Английский",
            russian: "Руский",
            ukrainian: "Украинский",
        },
        training: {
            programName: 'Название программы',
            plHolProgramName: 'Введите название программы',
            errorName: 'Имя должно содержать не менее 3 букв',
            next: 'Следующий',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Сложность',
            days: 'Дни',
            exercises: 'Упражнения',
            aerobicInfo: 'Aerobic - фитнес, кардио тренировки',
            anaerobicInfo: 'Anaerobic - силовые тренировки',
            crossfitInfo: 'CrossFit - смешанная тренировка, аэробная + анаэробная',
            selectType: 'Выберите тип программы',
            beginner: 'Начинающий',
            intermediate: 'Средний',
            advanced: 'Продвинутый',
            expert: 'Эксперт',
            professional: 'Профессиональный',
            selectDifficulty: 'Выберите уровень сложности',
            day: 'день',
            changeDay: 'Сколько тренировочных дней в неделю?',
            generalTraining: 'дневная общая тренировка',
            splitTraining: 'дневная сплит тренировка',
            create: 'Создать',
            editExercises: 'Редактировать упражнения',
            addExercises: 'Добавить упражнения',
            cancel: 'Отменить',
            confirm: 'Подтвердить',
            createProgram: 'Создать новую программу',
            myPrograms: 'Мои программы',
            secondaryMuscles: 'Вторичные мышцы',
            compound: 'Многосуставное',
            isolation: 'Изоляционное',
            none: 'Нету',
            finished: 'Закончил тренировку в -',
            all: 'Все',
            chest: 'Грудные',
            backMus: 'Спина',
            biceps: 'Бицепс',
            triceps: 'Трицепс',
            shoulders: 'Плечи',
            legs: 'Ноги',
            abs: 'Прес',
        }
    };

    const ua = {
        base: {
            login: 'Вхід',
            signUp: 'Реєстрація',
            profile: 'Профіль',
            training: 'Тренування',
            users: 'Користувачі',
            complexes: 'Комплекси',
            Programs: 'Програми',
            Wiki: 'Wiki',
            authorization: 'Авторизація',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше Ім\'я',
            lblLastName: 'Ваше призвіще',
            plHolName: 'Ім\'я',
            plHolLastName: 'Призвіще',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Якщо у вас немає облікового запису',
            haveAcc: 'Якщо у вас є обліковий запис',
            allUsers: 'Всі користувачі',
            edit: 'Редагувати',
            save: 'Зберегти',
            cancelRequest: 'Скасувати запит',
            removeFriend: 'Видалити друга',
            addFriends: 'Додати до друзів',
            settings: 'Налаштування',
            theme: 'Тема',
        },
        settings: {
            language: 'Мова',
            profile: 'Профіль',
            english: "Англійська",
            russian: "Російська",
            ukrainian: "Українська",
        },
        training: {
            programName: 'Назва програми',
            plHolProgramName: 'Введіть назву програми',
            errorName: 'Ім\'я повинно містити щонайменше 3 літери',
            next: 'Далі',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Складність',
            days: 'Дні',
            exercises: 'Вправи',
            aerobicInfo: 'Aerobic - фітнес, кардіо тренування',
            anaerobicInfo: 'Anaerobic - силові тренування',
            crossfitInfo: 'CrossFit - змішане тренування, аеробне + анаеробне',
            selectType: 'Виберіть тип програми',
            beginner: 'Початківець',
            intermediate: 'Середній',
            advanced: 'Просунутий',
            expert: 'Експерт',
            professional: 'Професійний',
            selectDifficulty: 'Виберіть рівень складності',
            day: 'день',
            changeDay: 'Скільки тренувальних днів на тиждень?',
            generalTraining: 'денне загальне навчання',
            splitTraining: 'денне спліт-тренування',
            create: 'Створити',
            editExercises: 'Редагувати вправи',
            addExercises: 'Додати вправи',
            cancel: 'Відмінити',
            confirm: 'Підтвердити',
            createProgram: 'Створити нову програму',
            myPrograms: 'Мої програми',
            secondaryMuscles: 'Вторинні м\'язи',
            compound: 'Багатосуставне',
            isolation: 'Ізоляційне',
            none: 'Немає',
            finished: 'Закінчив тренування в -',
            all: 'Все',
            chest: 'Грудні',
            backMus: 'Спина',
            biceps: 'Біцепс',
            triceps: 'Тріцепс',
            shoulders: 'Плечі',
            legs: 'Ноги',
            abs: 'Прес',
        }
    };

    switch (value) {
        case 'eng' : return eng;
        case 'rus' : return rus;
        case 'ukr' : return ua;
    }
}