import {AppLanguage} from './defaultLanguage';

export const getLanguages = (value: AppLanguage | string = 'eng') => {
    const eng = {
        base: {
            login: 'Login',
            signUp: 'Sign up',
            profile: 'Profile',
            training: 'Training',
            users: 'Users',
            complexes: 'Complexes',
            programs: 'Programs',
            Wiki: 'Wiki',
            authorization: 'Authorization',
            lblEmail: 'Your E-mail',
            lblPass: 'Your password',
            lblName: 'Your first name',
            lblLastName: 'Your last name',
            plHolName: 'Name',
            plHolLastName: 'Last name',
            plHolEmail: 'E-mail',
            plHolPass: 'Password',
            notHaveAcc: 'If you don\'t have an account',
            haveAcc: 'If you have an account',
            allUsers: 'All users',
            searchUsers: 'Search users',
            noUsersMatch: 'No users match "{value}".',
            edit: 'Edit',
            save: 'Save',
            none: 'None',
            cancelRequest: 'Cancel request',
            removeFriend: 'Remove friend',
            addFriends: 'Add to friends',
            settings: 'Settings',
            theme: 'Theme',
            seeAllFriends: 'See all friends',
            friends: 'Friends',
            browseUsers: 'Find new friends',
            records: 'Records',
            trainings: 'Trainings',
            noRecordsYet: 'No one has logged a weight yet.',
            showMore: 'Show more',
            kg: 'kg',
            requests: 'Requests',
            signOut: 'Sign out',
            oops: 'Oops: ',
            tryAgain: 'Try again',
            authWithGoogle: 'Auth with Google',
            installApp: 'Install CoreFit as an app',
            install: 'Install',
            loading: 'Loading...',
            friendRequestsLabel: 'Friend Requests ({value})',
            accept: 'Accept',
            decline: 'Decline',
            messages: 'Messages',
            messagesComingSoon: 'Coming soon — you\'ll be able to message friends directly from here.',
            friendRequestsTitle: 'Friend requests',
            noFriendRequests: 'No pending friend requests.',
            trainerRequestsTitle: 'Trainer requests',
            noTrainerRequests: 'No pending trainer requests.',
            addAsTrainer: 'Add as trainer',
            pending: 'Pending',
            yourTrainer: 'Your trainer',
            yourClient: 'Your client',
            removeFriendTitle: 'Remove friend?',
            removeFriendText: 'You will need to send a new request to become friends again.',
            removeTrainerTitle: 'Remove trainer?',
            removeTrainerText: 'They will no longer be able to edit your program.',
            removeClientTitle: 'Remove client?',
            removeClientText: 'You will no longer be able to edit their program.',
        },
        settings: {
            language: 'Language',
            profile: 'Profile',
            english: 'English',
            russian: 'Russian',
            ukrainian: 'Ukrainian',
            poland: 'Poland',
            trainerSection: 'Trainer',
            trainerToggle: 'I am a trainer',
            trainerHint: 'Lets friends invite you to be their trainer, and lets you create global programs.',
        },
        training: {
            programName: 'Name of program',
            plHolProgramName: 'Enter the program name',
            errorName: 'The name must contain at least 3 letters',
            next: 'Next',
            back: 'Back',
            name: 'Name',
            type: 'Type',
            difficulty: 'Difficulty',
            days: 'Days',
            exercises: 'Exercises',
            aerobicInfo: 'Aerobic - fitness, cardio training',
            anaerobicInfo: 'Anaerobic - strength training',
            crossfitInfo: 'CrossFit - mixed training, aerobic + anaerobic',
            selectType: 'Select Program Type',
            beginner: 'Beginner',
            intermediate: 'Intermediate',
            advanced: 'Advanced',
            expert: 'Expert',
            professional: 'Professional',
            selectDifficulty: 'Select Difficulty Level',
            day: 'day',
            changeDay: 'How many training days per week?',
            generalTraining: 'day general training',
            splitTraining: 'day split workout',
            create: 'Create',
            editExercises: 'Edit Exercises',
            addExercises: 'Add exercises',
            cancel: 'Cancel',
            confirm: 'Confirm',
            createProgram: 'Create new program',
            myPrograms: 'My programs',
            secondaryMuscles: 'Secondary muscles',
            compound: 'Compound',
            none: 'None',
            finished: 'Finished training in -',
            all: 'All',
            chest: 'Chest',
            backMus: 'Back',
            biceps: 'Biceps',
            triceps: 'Triceps',
            shoulders: 'Shoulders',
            legs: 'Legs',
            abs: 'Abs',
            complete: 'Complete',
            aerobic: 'Aerobic',
            anaerobic: 'Anaerobic',
            crossfit: 'Crossfit',
            notHavePrograms: 'You don\'t have any programs yet',
            notHaveProgramsUser: 'The user has no programs',
            removeProgramTitle: 'Uninstalling the program',
            removeProgramText: 'Are you sure you want to delete the program? All its settings and training history will also be deleted along with the program',
            author: 'Author',
            isolation: 'Isolation',
            searchExercises: 'Search exercises',
            noExercisesMatch: 'No exercises match "{value}".',
            editTrainingProgram: 'Edit Training Program',
            createTrainingProgram: 'Create Training Program',
            createGlobalProgram: 'Create global program',
            pleaseLoginFirst: 'Please login first',
            addToMyPrograms: 'Add to my programs',
            removeFromMyPrograms: 'Remove from my programs',
            noGlobalProgramsFound: 'No global programs found.',
            dayNumber: 'Day {value}',
            programNotFound: 'Program not found',
            dayCount: { one: 'day', few: 'days', many: 'days', other: 'days' },
            confirmRemovalTitle: 'Save changes?',
            confirmRemovalBody: 'This will permanently remove {value} from this program, along with any related training history. Continue?',
        },
    };

    const rus = {
        base: {
            login: 'Войти',
            signUp: 'Регистрация',
            profile: 'Профиль',
            training: 'Тренировка',
            users: 'Пользователи',
            complexes: 'Комплексы',
            programs: 'Програмы',
            Wiki: 'Wiki',
            authorization: 'Авторизация',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше имя',
            lblLastName: 'Ваша фамилия',
            plHolName: 'Имя',
            plHolLastName: 'Фамилия',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Если у вас нет учетной записи',
            haveAcc: 'Если у вас есть аккаунт',
            allUsers: 'Все пользователи',
            searchUsers: 'Поиск пользователей',
            noUsersMatch: 'Нет пользователей по запросу «{value}».',
            edit: 'Редактировать',
            save: 'Сохранить',
            cancelRequest: 'Отменить запрос',
            removeFriend: 'Удалить друга',
            addFriends: 'Добавить в друзья',
            settings: 'Настройки',
            theme: 'Тема',
            seeAllFriends: 'Посмотреть всех друзей',
            friends: 'Друзья',
            browseUsers: 'Найти новых друзей',
            records: 'Рекорды',
            trainings: 'Тренировки',
            noRecordsYet: 'Пока никто не залогировал вес.',
            showMore: 'Показать ещё',
            kg: 'кг',
            requests: 'Запросы',
            signOut: 'Выйти',
            oops: 'Упс: ',
            tryAgain: 'Попробовать снова',
            authWithGoogle: 'Войти через Google',
            installApp: 'Установите CoreFit как приложение',
            install: 'Установить',
            loading: 'Загрузка...',
            friendRequestsLabel: 'Запросы в друзья ({value})',
            accept: 'Принять',
            decline: 'Отклонить',
            messages: 'Сообщения',
            messagesComingSoon: 'Скоро — вы сможете отправлять сообщения друзьям прямо отсюда.',
            friendRequestsTitle: 'Запросы в друзья',
            noFriendRequests: 'Нет активных запросов в друзья.',
            trainerRequestsTitle: 'Запросы на тренерство',
            noTrainerRequests: 'Нет входящих запросов на тренерство.',
            addAsTrainer: 'Добавить в тренеры',
            pending: 'Ожидает',
            yourTrainer: 'Ваш тренер',
            yourClient: 'Ваш клиент',
            removeFriendTitle: 'Удалить друга?',
            removeFriendText: 'Чтобы снова стать друзьями, придётся отправить новый запрос.',
            removeTrainerTitle: 'Удалить тренера?',
            removeTrainerText: 'Он больше не сможет редактировать вашу программу.',
            removeClientTitle: 'Удалить клиента?',
            removeClientText: 'Вы больше не сможете редактировать его программу.',
        },
        settings: {
            language: 'Язык',
            profile: 'Профиль',
            english: 'Английский',
            russian: 'Руский',
            ukrainian: 'Украинский',
            poland: 'Польский',
            trainerSection: 'Тренер',
            trainerToggle: 'Я тренер',
            trainerHint: 'Позволяет друзьям приглашать вас стать их тренером, а также создавать глобальные программы.',
        },
        training: {
            programName: 'Название программы',
            plHolProgramName: 'Введите название программы',
            errorName: 'Имя должно содержать не менее 3 букв',
            next: 'Следующий',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Сложность',
            days: 'Дни',
            exercises: 'Упражнения',
            aerobicInfo: 'Aerobic - фитнес, кардио тренировки',
            anaerobicInfo: 'Anaerobic - силовые тренировки',
            crossfitInfo: 'CrossFit - смешанная тренировка, аэробная + анаэробная',
            selectType: 'Выберите тип программы',
            beginner: 'Начинающий',
            intermediate: 'Средний',
            advanced: 'Продвинутый',
            expert: 'Эксперт',
            professional: 'Профессиональный',
            selectDifficulty: 'Выберите уровень сложности',
            day: 'день',
            changeDay: 'Сколько тренировочных дней в неделю?',
            generalTraining: 'дневная общая тренировка',
            splitTraining: 'дневная сплит тренировка',
            create: 'Создать',
            editExercises: 'Редактировать упражнения',
            addExercises: 'Добавить упражнения',
            cancel: 'Отменить',
            confirm: 'Подтвердить',
            createProgram: 'Создать новую программу',
            myPrograms: 'Мои программы',
            secondaryMuscles: 'Вторичные мышцы',
            compound: 'Многосуставное',
            isolation: 'Изоляционное',
            none: 'Нету',
            finished: 'Закончил тренировку -',
            all: 'Все',
            chest: 'Грудные',
            backMus: 'Спина',
            biceps: 'Бицепс',
            triceps: 'Трицепс',
            shoulders: 'Плечи',
            legs: 'Ноги',
            abs: 'Прес',
            complete: 'Завершить',
            aerobic: 'Аэробная',
            anaerobic: 'Анаэробная',
            crossfit: 'Кроссфит',
            notHavePrograms: 'У вас пока нет ни одной программы',
            notHaveProgramsUser: 'У пользователя нет программ',
            removeProgramTitle: 'Удаление программы',
            removeProgramText: 'Вы уверены, что хотите удалить программу? Всея ее упражнения и история тренировок также будут удалены вместе с программой',
            author: 'Автор',
            searchExercises: 'Поиск упражнений',
            noExercisesMatch: 'Нет упражнений, соответствующих "{value}".',
            editTrainingProgram: 'Редактировать тренировочную программу',
            createTrainingProgram: 'Создать тренировочную программу',
            createGlobalProgram: 'Создать глобальную программу',
            pleaseLoginFirst: 'Сначала войдите',
            addToMyPrograms: 'Добавить в мои программы',
            removeFromMyPrograms: 'Удалить из моих программ',
            noGlobalProgramsFound: 'Глобальные программы не найдены.',
            dayNumber: 'День {value}',
            programNotFound: 'Программа не найдена',
            dayCount: { one: 'день', few: 'дня', many: 'дней', other: 'дня' },
            confirmRemovalTitle: 'Сохранить изменения?',
            confirmRemovalBody: 'Это навсегда удалит {value} из этой программы, вместе со связанной историей тренировок. Продолжить?',
        },
    };

    const ua = {
        base: {
            login: 'Вхід',
            signUp: 'Реєстрація',
            profile: 'Профіль',
            training: 'Тренування',
            users: 'Користувачі',
            complexes: 'Комплекси',
            programs: 'Програми',
            Wiki: 'Wiki',
            authorization: 'Авторизація',
            lblEmail: 'Ваш E-mail',
            lblPass: 'Ваш пароль',
            lblName: 'Ваше Ім\'я',
            lblLastName: 'Ваше прізвище',
            plHolName: 'Ім\'я',
            plHolLastName: 'Прізвище',
            plHolEmail: 'E-mail',
            plHolPass: 'Пароль',
            notHaveAcc: 'Якщо у вас немає облікового запису',
            haveAcc: 'Якщо у вас є обліковий запис',
            allUsers: 'Всі користувачі',
            searchUsers: 'Пошук користувачів',
            noUsersMatch: 'Немає користувачів за запитом «{value}».',
            edit: 'Редагувати',
            save: 'Зберегти',
            cancelRequest: 'Скасувати запит',
            removeFriend: 'Видалити друга',
            addFriends: 'Додати до друзів',
            settings: 'Налаштування',
            theme: 'Тема',
            seeAllFriends: 'Переглянути всіх друзів',
            friends: 'Друзі',
            browseUsers: 'Знайти нових друзів',
            records: 'Рекорди',
            trainings: 'Тренування',
            noRecordsYet: 'Ще ніхто не залогував вагу.',
            showMore: 'Показати ще',
            kg: 'кг',
            requests: 'Запити',
            signOut: 'Вийти',
            oops: 'Ой: ',
            tryAgain: 'Спробувати знову',
            authWithGoogle: 'Увійти через Google',
            installApp: 'Встановіть CoreFit як додаток',
            install: 'Встановити',
            loading: 'Завантаження...',
            friendRequestsLabel: 'Запити в друзі ({value})',
            accept: 'Прийняти',
            decline: 'Відхилити',
            messages: 'Повідомлення',
            messagesComingSoon: 'Незабаром — ви зможете надсилати повідомлення друзям прямо звідси.',
            friendRequestsTitle: 'Запити в друзі',
            noFriendRequests: 'Немає активних запитів у друзі.',
            trainerRequestsTitle: 'Запити на тренерство',
            noTrainerRequests: 'Немає вхідних запитів на тренерство.',
            addAsTrainer: 'Додати у тренери',
            pending: 'Очікує',
            yourTrainer: 'Ваш тренер',
            yourClient: 'Ваш клієнт',
            removeFriendTitle: 'Видалити друга?',
            removeFriendText: 'Щоб знову стати друзями, доведеться надіслати новий запит.',
            removeTrainerTitle: 'Видалити тренера?',
            removeTrainerText: 'Він більше не зможе редагувати вашу програму.',
            removeClientTitle: 'Видалити клієнта?',
            removeClientText: 'Ви більше не зможете редагувати його програму.',
        },
        settings: {
            language: 'Мова',
            profile: 'Профіль',
            english: 'Англійська',
            russian: 'Російська',
            ukrainian: 'Українська',
            poland: 'Польський',
            trainerSection: 'Тренер',
            trainerToggle: 'Я тренер',
            trainerHint: 'Дозволяє друзям запрошувати вас стати їхнім тренером, а також створювати глобальні програми.',
        },
        training: {
            programName: 'Назва програми',
            plHolProgramName: 'Введіть назву програми',
            errorName: 'Ім\'я повинно містити щонайменше 3 літери',
            next: 'Далі',
            back: 'Назад',
            name: 'Назва',
            type: 'Тип',
            difficulty: 'Складність',
            days: 'Дні',
            exercises: 'Вправи',
            aerobicInfo: 'Aerobic - фітнес, кардіо тренування',
            anaerobicInfo: 'Anaerobic - силові тренування',
            crossfitInfo: 'CrossFit - змішане тренування, аеробне + анаеробне',
            selectType: 'Виберіть тип програми',
            beginner: 'Початківець',
            intermediate: 'Середній',
            advanced: 'Просунутий',
            expert: 'Експерт',
            professional: 'Професійний',
            selectDifficulty: 'Виберіть рівень складності',
            day: 'день',
            changeDay: 'Скільки тренувальних днів на тиждень?',
            generalTraining: 'денне загальне навчання',
            splitTraining: 'денне спліт-тренування',
            create: 'Створити',
            editExercises: 'Редагувати вправи',
            addExercises: 'Додати вправи',
            cancel: 'Відмінити',
            confirm: 'Підтвердити',
            createProgram: 'Створити нову програму',
            myPrograms: 'Мої програми',
            secondaryMuscles: 'Вторинні м\'язи',
            compound: 'Багатосуставне',
            isolation: 'Ізоляційне',
            none: 'Немає',
            finished: 'Закінчив тренування -',
            all: 'Все',
            chest: 'Грудні',
            backMus: 'Спина',
            biceps: 'Біцепс',
            triceps: 'Тріцепс',
            shoulders: 'Плечі',
            legs: 'Ноги',
            abs: 'Прес',
            complete: 'Завершити',
            aerobic: 'Аеробна',
            anaerobic: 'Анаеробна',
            crossfit: 'Кроссфіт',
            notHavePrograms: 'У вас ще немає жодних програм',
            notHaveProgramsUser: 'У користувача немає програм',
            removeProgramTitle: 'Видалення програми',
            removeProgramText: 'Ви впевнені, що хочете видалити програму? Усі її вправи та історія тренувань також будуть видалені разом із програмою',
            author: 'Автор',
            searchExercises: 'Пошук вправ',
            noExercisesMatch: 'Немає вправ, що відповідають "{value}".',
            editTrainingProgram: 'Редагувати тренувальну програму',
            createTrainingProgram: 'Створити тренувальну програму',
            createGlobalProgram: 'Створити глобальну програму',
            pleaseLoginFirst: 'Спершу увійдіть',
            addToMyPrograms: 'Додати до моїх програм',
            removeFromMyPrograms: 'Видалити з моїх програм',
            noGlobalProgramsFound: 'Глобальні програми не знайдено.',
            dayNumber: 'День {value}',
            programNotFound: 'Програму не знайдено',
            dayCount: { one: 'день', few: 'дні', many: 'днів', other: 'дня' },
            confirmRemovalTitle: 'Зберегти зміни?',
            confirmRemovalBody: 'Це назавжди видалить {value} з цієї програми разом із пов’язаною історією тренувань. Продовжити?',
        },
    };

    const pl = {
        base: {
            login: 'Zaloguj się',
            signUp: 'Zarejestruj się',
            profile: 'Profil',
            training: 'Trening',
            users: 'Użytkownicy',
            complexes: 'Kompleksy',
            programs: 'Programy',
            Wiki: 'Wiki',
            authorization: 'Autoryzacja',
            lblEmail: 'Twój e-mail',
            lblPass: 'Twoje hasło',
            lblName: 'Twoje imię',
            lblLastName: 'Twoje nazwisko',
            plHolName: 'Imię',
            plHolLastName: 'Nazwisko',
            plHolEmail: 'E-mail',
            plHolPass: 'Hasło',
            notHaveAcc: 'Jeśli nie masz konta',
            haveAcc: 'Jeśli masz konto',
            allUsers: 'Wszyscy użytkownicy',
            searchUsers: 'Szukaj użytkowników',
            noUsersMatch: 'Brak użytkowników pasujących do "{value}".',
            edit: 'Edytuj',
            save: 'Zapisz',
            none: 'Brak',
            cancelRequest: 'Anuluj prośbę',
            removeFriend: 'Usuń znajomego',
            addFriends: 'Dodaj do znajomych',
            settings: 'Ustawienia',
            theme: 'Motyw',
            seeAllFriends: 'Zobacz wszystkich znajomych',
            friends: 'Znajomi',
            browseUsers: 'Znajdź nowych znajomych',
            records: 'Rekordy',
            trainings: 'Treningi',
            noRecordsYet: 'Nikt jeszcze nie zapisał ciężaru.',
            showMore: 'Pokaż więcej',
            kg: 'kg',
            requests: 'Zaproszenia',
            signOut: 'Wyloguj się',
            oops: 'Ups: ',
            tryAgain: 'Spróbuj ponownie',
            authWithGoogle: 'Zaloguj się przez Google',
            installApp: 'Zainstaluj CoreFit jako aplikację',
            install: 'Zainstaluj',
            loading: 'Ładowanie...',
            friendRequestsLabel: 'Zaproszenia do znajomych ({value})',
            accept: 'Akceptuj',
            decline: 'Odrzuć',
            messages: 'Wiadomości',
            messagesComingSoon: 'Wkrótce — będziesz mógł wysyłać wiadomości do znajomych bezpośrednio stąd.',
            friendRequestsTitle: 'Zaproszenia do znajomych',
            noFriendRequests: 'Brak oczekujących zaproszeń do znajomych.',
            trainerRequestsTitle: 'Prośby o bycie trenerem',
            noTrainerRequests: 'Brak oczekujących próśb o bycie trenerem.',
            addAsTrainer: 'Dodaj jako trenera',
            pending: 'Oczekuje',
            yourTrainer: 'Twój trener',
            yourClient: 'Twój klient',
            removeFriendTitle: 'Usunąć znajomego?',
            removeFriendText: 'Aby ponownie zostać znajomymi, będziesz musiał wysłać nową prośbę.',
            removeTrainerTitle: 'Usunąć trenera?',
            removeTrainerText: 'Nie będzie już mógł edytować Twojego programu.',
            removeClientTitle: 'Usunąć klienta?',
            removeClientText: 'Nie będziesz już mógł edytować jego programu.',
        },
        settings: {
            language: 'Język',
            profile: 'Profil',
            english: 'Angielski',
            russian: 'Rosyjski',
            ukrainian: 'Ukraiński',
            poland: 'Polski',
            trainerSection: 'Trener',
            trainerToggle: 'Jestem trenerem',
            trainerHint: 'Pozwala znajomym zapraszać Cię na swojego trenera oraz tworzyć globalne programy.',
        },
        training: {
            programName: 'Nazwa programu',
            plHolProgramName: 'Wprowadź nazwę programu',
            errorName: 'Nazwa musi zawierać co najmniej 3 litery',
            next: 'Dalej',
            back: 'Wstecz',
            name: 'Nazwa',
            type: 'Typ',
            difficulty: 'Poziom trudności',
            days: 'Dni',
            exercises: 'Ćwiczenia',
            aerobicInfo: 'Aerobik - fitness, trening cardio',
            anaerobicInfo: 'Anaerobowy - trening siłowy',
            crossfitInfo: 'CrossFit - trening mieszany, aerobowy + anaerobowy',
            selectType: 'Wybierz typ programu',
            beginner: 'Początkujący',
            intermediate: 'Średni',
            advanced: 'Zaawansowany',
            expert: 'Ekspert',
            professional: 'Profesjonalista',
            selectDifficulty: 'Wybierz poziom trudności',
            day: 'dzień',
            changeDay: 'Ile dni treningowych w tygodniu?',
            generalTraining: 'ogólny trening dzienny',
            splitTraining: 'trening dzielony dzienny',
            create: 'Utwórz',
            editExercises: 'Edytuj ćwiczenia',
            addExercises: 'Dodaj ćwiczenia',
            cancel: 'Anuluj',
            confirm: 'Potwierdź',
            createProgram: 'Utwórz nowy program',
            myPrograms: 'Moje programy',
            secondaryMuscles: 'Mięśnie pomocnicze',
            compound: 'Złożone',
            isolation: 'Izolowane',
            none: 'Brak',
            finished: 'Zakończono trening -',
            all: 'Wszystko',
            chest: 'Klatka piersiowa',
            backMus: 'Plecy',
            biceps: 'Biceps',
            triceps: 'Triceps',
            shoulders: 'Barki',
            legs: 'Nogi',
            abs: 'Brzuch',
            complete: 'Zakończ',
            aerobic: 'Aerobowy',
            anaerobic: 'Anaerobowy',
            crossfit: 'CrossFit',
            notHavePrograms: 'Nie masz jeszcze żadnych programów',
            notHaveProgramsUser: 'Użytkownik nie ma żadnych programów',
            removeProgramTitle: 'Odinstalowywanie programu',
            removeProgramText: 'Czy na pewno chcesz usunąć aplikację? Wszystkie jej ćwiczenia i historia treningów zostaną również usunięte wraz z aplikacją',
            author: 'Autor',
            searchExercises: 'Szukaj ćwiczeń',
            noExercisesMatch: 'Brak ćwiczeń pasujących do "{value}".',
            editTrainingProgram: 'Edytuj program treningowy',
            createTrainingProgram: 'Utwórz program treningowy',
            createGlobalProgram: 'Utwórz program globalny',
            pleaseLoginFirst: 'Najpierw się zaloguj',
            addToMyPrograms: 'Dodaj do moich programów',
            removeFromMyPrograms: 'Usuń z moich programów',
            noGlobalProgramsFound: 'Nie znaleziono programów globalnych.',
            dayNumber: 'Dzień {value}',
            programNotFound: 'Nie znaleziono programu',
            dayCount: { one: 'dzień', few: 'dni', many: 'dni', other: 'dnia' },
            confirmRemovalTitle: 'Zapisać zmiany?',
            confirmRemovalBody: 'To trwale usunie {value} z tego programu, wraz z powiązaną historią treningów. Kontynuować?',
        },
    };

    switch (value) {
        case 'eng':
            return eng;
        case 'rus':
            return rus;
        case 'ukr':
            return ua;
        case 'pl':
            return pl;
        default:
            return eng;
    }
};